### ISSUE TITLE
Enrollments not loading in member profile

### ISSUE THREAD

**Issue by eezing** [workflow-testies/inbox#2]
Behavior:
Given an existing member that has 5 enrollments
When I goto page https://testies/member/abc123
Then the enrollments are not showing on page

Expected Behavior:
Given an existing member that has enrollments
When I goto page https://testies/member/abc123
Then the enrollments should show 5 enrollments in enrollments section

**Comment by eezing** [comment]
The browser network log shows a 500 error. Looks like an API problem.

**Comment by donaldhansen** [comment]
asdf
